import path from 'node:path';

import * as ts from 'typescript';

import type { AnalysisOptions } from './interfaces.js';

export const DEFAULT_OPTS: AnalysisOptions = {
  minFunctionStatements: 6,
  minFlowStatements: 6,
  root: process.cwd(),
  includeTests: false,
  emitTree: true,
  json: false,
  graph: false,
  out: null,
  treeDepth: 4,
  findingsLimit: Infinity,
  parser: 'auto',
  criticalComplexityThreshold: 30,
  deepLinkTopN: 12,
  packageRoot: path.join(process.cwd(), 'packages'),
  ignoreDirs: new Set([
    '.git',
    '.next',
    '.yarn',
    '.cache',
    '.octocode',
    'node_modules',
    'dist',
    'coverage',
    'out',
  ]),
  couplingThreshold: 15,
  fanInThreshold: 20,
  fanOutThreshold: 15,
  godModuleStatements: 500,
  godModuleExports: 20,
  godFunctionStatements: 100,
  godFunctionMiThreshold: 10,
  cognitiveComplexityThreshold: 15,
  barrelSymbolThreshold: 30,
  layerOrder: [],
  parameterThreshold: 5,
  halsteadEffortThreshold: 500_000,
  maintainabilityIndexThreshold: 20,
  anyThreshold: 5,
  flowDupThreshold: 3,
  maxRecsPerCategory: 2,
  features: null,
  scope: null,
  scopeSymbols: null,
  noCache: false,
  clearCache: false,
  semantic: false,
  overrideChainThreshold: 3,
  shotgunThreshold: 8,
  sdpMinDelta: 0.15,
  sdpMaxSourceInstability: 0.6,
  secretEntropyThreshold: 4.5,
  secretMinLength: 20,
  similarityThreshold: 0.85,
  mockThreshold: 10,
  noDiversify: false,
  graphAdvanced: false,
  flow: false,
};

export const PILLAR_CATEGORIES: Record<string, string[]> = {
  architecture: [
    'dependency-cycle',
    'dependency-critical-path',
    'dependency-test-only',
    'architecture-sdp-violation',
    'high-coupling',
    'god-module-coupling',
    'orphan-module',
    'unreachable-module',
    'layer-violation',
    'low-cohesion',
    'mega-folder',
    'distance-from-main-sequence',
    'feature-envy',
    'untested-critical-code',
    'over-abstraction',
    'concrete-dependency',
    'circular-type-dependency',
    'shotgun-surgery',
    'import-side-effect-risk',
    'cycle-cluster',
    'broker-module',
    'bridge-module',
    'package-boundary-chatter',
    'startup-risk-hub',
    'namespace-import',
    'commonjs-in-esm',
    'export-star-leak',
    'mixed-module-format',
  ],
  'code-quality': [
    'duplicate-function-body',
    'duplicate-flow-structure',
    'function-optimization',
    'cognitive-complexity',
    'god-module',
    'god-function',
    'halstead-effort',
    'low-maintainability',
    'excessive-parameters',
    'unsafe-any',
    'empty-catch',
    'switch-no-default',
    'unused-parameter',
    'deep-override-chain',
    'interface-compliance',
    'type-assertion-escape',
    'promise-misuse',
    'narrowable-type',
    'missing-error-boundary',
    'await-in-loop',
    'sync-io',
    'uncleared-timer',
    'listener-leak-risk',
    'unbounded-collection',
    'similar-function-body',
    'message-chain',
  ],
  'dead-code': [
    'dead-export',
    'dead-re-export',
    're-export-duplication',
    're-export-shadowed',
    'unused-npm-dependency',
    'package-boundary-violation',
    'barrel-explosion',
    'unused-import',
    'orphan-implementation',
    'move-to-caller',
    'semantic-dead-export',
    'dead-file',
  ],
  security: [
    'hardcoded-secret',
    'eval-usage',
    'unsafe-html',
    'sql-injection-risk',
    'unsafe-regex',
    'prototype-pollution-risk',
    'unvalidated-input-sink',
    'input-passthrough-risk',
    'path-traversal-risk',
    'command-injection-risk',
    'debug-log-leakage',
    'sensitive-data-logging',
  ],
  'test-quality': [
    'low-assertion-density',
    'test-no-assertion',
    'excessive-mocking',
    'shared-mutable-state',
    'missing-test-cleanup',
    'focused-test',
    'fake-timer-no-restore',
    'missing-mock-restoration',
  ],
};

export const ALL_CATEGORIES = new Set(Object.values(PILLAR_CATEGORIES).flat());

export const SEMANTIC_CATEGORIES = new Set([
  'over-abstraction',
  'concrete-dependency',
  'circular-type-dependency',
  'unused-parameter',
  'deep-override-chain',
  'interface-compliance',
  'unused-import',
  'orphan-implementation',
  'shotgun-surgery',
  'move-to-caller',
  'narrowable-type',
  'semantic-dead-export',
]);
export const ALLOWED_EXTS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
]);
export const IMPORT_RESOLVE_EXTS = [
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.d.ts',
];

export const TS_CONTROL_KINDS = new Set<number>([
  ts.SyntaxKind.IfStatement,
  ts.SyntaxKind.SwitchStatement,
  ts.SyntaxKind.TryStatement,
  ts.SyntaxKind.ForStatement,
  ts.SyntaxKind.WhileStatement,
  ts.SyntaxKind.DoStatement,
  ts.SyntaxKind.ForOfStatement,
  ts.SyntaxKind.ForInStatement,
  ts.SyntaxKind.ConditionalExpression,
]);

export const TS_TREE_SITTER_CONTROL_TYPES = new Set<string>([
  'if_statement',
  'switch_statement',
  'try_statement',
  'for_statement',
  'while_statement',
  'do_statement',
  'for_in_statement',
  'for_of_statement',
  'for_await_statement',
  'conditional_expression',
  'conditional_expression?',
  'catch_clause',
]);

export const TS_TREE_SITTER_FUNCTION_TYPES = new Set<string>([
  'function_declaration',
  'function',
  'generator_function',
  'generator_function_declaration',
  'method_definition',
  'arrow_function',
  'function_expression',
]);

interface SeverityOrder {
  [key: string]: number;
}

export const SEVERITY_ORDER: SeverityOrder = {
  critical: 4,
  high: 3,
  medium: 2,
  low: 1,
  info: 0,
};
