/**
 * unified-agent-tool.ts — Phase 4 facade: RFC tool-surface-unification.
 *
 * Registers a single public tool named `agent` that wraps:
 *   spawn   → typed profiles (researcher/planner/architect/browser/custom)
 *   inspect → list all agents or status of one
 *   wait    → wait for a worker turn or return a live snapshot after silence
 *   message → send/followUp to a live agent
 *   steer   → redirect in-flight turn or queue a follow-up
 *   abort   → graceful RPC interrupt without terminating the process
 *   kill    → terminate a worker process
 *
 * Agent state is projected from agent-tools.ts into this public facade.
 *
 * Browser profile delegates to routeTask + buildSpawnConfig (exported from
 * browser-agent-tool.ts) for CDP domain routing and system-prompt construction.
 *
 * Same-batch cross-reference guard: a batch that contains at least one `spawn`
 * query AND at least one lifecycle query with a non-empty `agentId` is rejected
 * before any side effect, because the caller cannot know the IDs that would be
 * generated by the spawns in the same call.
 *
 */

import type {
  ToolDefinition,
  ToolCallResult,
  PiContext,
  PiTheme,
} from '../types.js';
import type { registerUniqueTool } from './octocode-tools.js';
import {
  isSubagentProcess,
  prepareSpawnAgentParams,
  executeAgentLifecycle,
  spawnRpcAgent,
  refreshAgentLedgerUi,
  listWorkerLedgerEntries,
  findLivePlanWorker,
  type SpawnAgentParams,
} from './agent-tools.js';
import {
  SUBAGENT_REGISTRY,
  loadSystemPrompt,
  resolveSubagentSkills,
  type SubagentConfig,
  type SubagentName,
} from '../subagents.js';
import { routeTask, buildSpawnConfig } from './browser-agent-tool.js';
import { connectToChrome, cleanupConnection } from '../chrome-debug.js';
import { SCHEME_REGISTRY } from '../chrome-debug-schemes.js';
import type { ChromeDebugParams } from '../chrome-debug-schemes.js';
import {
  buildQueryEnvelopeSchema,
  executeQueryBatch,
  type QueryRecord,
} from './query-envelope.js';
import { stringEnumSchema } from './schema-helpers.js';
import { getRandomAgentName } from '../agentNames.js';
import { makeComponentRenderer } from './render-helpers.js';
import { truncateToWidth } from '../tui/width.js';
import { CLI_GLYPH } from '../tui/cli-design.js';
import { paint } from '../tui/palette.js';
import {
  getToolEffect,
  registerAgentToolEffectResolver,
  type ToolEffect,
} from './plan-mode.js';
import { activePlanScope } from './active-plan.js';
import { getCurrentPlanReadModel } from './plan-read-model.js';

type TypeBoxBuilder = (typeof import('typebox'))['Type'];
type RegisterFn = typeof registerUniqueTool;

// ─── Profile & operation constants ────────────────────────────────────────────

/** Typed profiles backed by SUBAGENT_REGISTRY. */
const TYPED_REGISTRY_PROFILES = ['researcher', 'planner', 'architect'] as const;

/** All public profiles exposed on the `agent` tool. */
export const AGENT_PROFILES = [
  ...TYPED_REGISTRY_PROFILES,
  'browser',
  'custom',
] as const;
export type AgentProfile = (typeof AGENT_PROFILES)[number];

/** All operations exposed on the `agent` tool. */
export const AGENT_OPERATIONS = [
  'spawn',
  'inspect',
  'wait',
  'message',
  'steer',
  'abort',
  'kill',
] as const;
export type AgentOperation = (typeof AGENT_OPERATIONS)[number];

// ─── Typed-profile → subagent-registry mapping ───────────────────────────────

const PROFILE_TO_SUBAGENT: Record<
  (typeof TYPED_REGISTRY_PROFILES)[number],
  SubagentName
> = {
  researcher: 'researcher',
  planner: 'planner',
  architect: 'architect',
};

const DYNAMIC_CHILD_TOOLS = new Set([
  'agent',
  'calltool',
  'mcptool',
  'skill',
]);

function isQueryRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function resolveTypedProfileEffect(profile: (typeof TYPED_REGISTRY_PROFILES)[number]): ToolEffect | undefined {
  const config = SUBAGENT_REGISTRY[PROFILE_TO_SUBAGENT[profile]] as SubagentConfig | undefined;
  if (!config || !Array.isArray(config.tools)) return undefined;

  let resolved: ToolEffect = 'coordination-write';
  for (const rawName of config.tools) {
    if (typeof rawName !== 'string' || !rawName.trim()) return undefined;
    const name = rawName.trim();
    const effect = DYNAMIC_CHILD_TOOLS.has(name.toLowerCase())
      ? 'external-effect'
      : getToolEffect(name);
    if (!effect) return undefined;
    if (effect === 'external-effect') return effect;
    if (effect === 'workspace-write') resolved = effect;
  }
  return resolved;
}

/** Resolve the effect of the complete ordered agent batch before any item runs. */
export function resolveAgentBatchEffect(input?: Record<string, unknown>): ToolEffect | undefined {
  const values = input?.['queries'];
  if (!Array.isArray(values) || values.length === 0) return undefined;

  let resolved: ToolEffect = 'coordination-write';
  for (const value of values) {
    if (!isQueryRecord(value)) return undefined;
    const operation = typeof value['type'] === 'string' ? value['type'] : undefined;
    if (!operation || !(AGENT_OPERATIONS as readonly string[]).includes(operation)) return undefined;
    if (operation !== 'spawn') continue;

    if (!String(value['task'] ?? '').trim()) return undefined;
    const profile = typeof value['profile'] === 'string' ? value['profile'] : 'custom';
    if (!(AGENT_PROFILES as readonly string[]).includes(profile)) return undefined;
    if (profile === 'custom' || profile === 'browser') return 'external-effect';

    const profileEffect = resolveTypedProfileEffect(profile as (typeof TYPED_REGISTRY_PROFILES)[number]);
    if (!profileEffect) return undefined;
    if (profileEffect === 'external-effect') return profileEffect;
    if (profileEffect === 'workspace-write') resolved = profileEffect;
  }
  return resolved;
}

registerAgentToolEffectResolver(resolveAgentBatchEffect);

// ─── Same-batch cross-reference guard ────────────────────────────────────────

/**
 * Reject a batch that mixes `spawn` (which generates new IDs at runtime) with
 * lifecycle queries that supply an explicit `agentId`, because the caller cannot
 * know a freshly generated ID before the call completes.
 *
 * Multiple independent spawns are allowed. Multiple lifecycle ops on
 * pre-existing agents are allowed. Only the ambiguous mixed case is blocked.
 */
export function rejectCrossBatchReference(queries: QueryRecord[]): void {
  const hasSpawn = queries.some((q) => (q['type'] as string) === 'spawn');
  if (!hasSpawn) return;

  const lifecycleWithId = queries.filter(
    (q) =>
      (q['type'] as string) !== 'spawn' &&
      typeof q['agentId'] === 'string' &&
      (q['agentId'] as string).trim().length > 0,
  );

  if (lifecycleWithId.length > 0) {
    const ops = lifecycleWithId.map((q) => q['type'] as string).join(', ');
    throw new Error(
      `Same-batch cross-reference rejected: a batch containing spawn cannot also ` +
      `reference an agentId in lifecycle queries (${ops}). ` +
      `Spawn workers in one call, then use the returned agentId in a subsequent call.`,
    );
  }
}

// ─── Spawn dispatch ───────────────────────────────────────────────────────────

function resolvePlanAssignment(planStep: string, ctx?: PiContext, expectedPlanId?: string) {
  const scope = activePlanScope(ctx);
  const plan = getCurrentPlanReadModel(ctx, scope);
  if (expectedPlanId && plan.planId !== expectedPlanId) throw new Error('Parent plan changed during worker preparation; inspect the current plan before delegating.');
  if (plan.phase !== 'executing') throw new Error('A plan assignment requires the parent plan to be executing. Start the accepted plan before delegating its tasks.');
  if (plan.pendingInteractionIds.length > 0) throw new Error('Resolve pending plan interactions before delegating a task.');
  const task = plan.tasks.find((candidate) => candidate.id === planStep);
  if (!task) throw new Error(`planStep must be an existing stable task id in the current plan: ${planStep}`);
  if (task.status !== 'doing') throw new Error(`Plan task ${planStep} must be doing before delegation; start its runnable step first.`);
  if (!task.dependsOn.every((index) => plan.tasks.find((candidate) => candidate.index === index)?.status === 'done')) {
    throw new Error(`Plan task ${planStep} has unfinished dependencies.`);
  }
  const owner = findLivePlanWorker(scope, plan.planId, task.id);
  if (owner) throw new Error(`Plan task ${planStep} already has live worker ${owner}; collect or continue that worker before assigning another.`);
  return { scope, planId: plan.planId, task };
}

export async function executeSpawnQuery(
  query: QueryRecord,
  ctx?: PiContext,
  signal?: AbortSignal,
): Promise<ToolCallResult> {
  signal?.throwIfAborted();
  const profile = (query['profile'] as AgentProfile | undefined) ?? 'custom';
  const task = String(query['task'] ?? '').trim();
  const context = query['context'] as string | undefined;
  const name = query['name'] as string | undefined;
  const model = query['model'] as string | undefined;
  const provider = query['provider'] as string | undefined;
  const thinking = query['thinking'] as string | undefined;
  const cwd = query['cwd'] as string | undefined;
  const isolation = query['isolation'] as SpawnAgentParams['isolation'];
  const includeUncommitted = query['includeUncommitted'] as boolean | undefined;
  const planStep = (query['planStep'] as string | undefined)?.trim() || undefined;

  if (!task) {
    throw new Error('agent spawn requires a non-empty task.');
  }
  const assignment = planStep ? resolvePlanAssignment(planStep, ctx) : undefined;

  const fullTask = context
    ? `## Context\n${(context as string).trim()}\n\n## Task\n${task}`
    : task;

  let spawnParams: SpawnAgentParams;

  if (profile === 'browser') {
    const port = (query['port'] as number | undefined) ?? 9222;
    const url = query['url'] as string | undefined;
    const launch = query['launch'] === true;
    const headless = query['headless'] !== false;
    const runNow = query['runNow'] !== false;
    const durationMs = (query['durationMs'] as number | undefined) ?? 5000;
    const workspaceCwd = query['workspaceCwd'] as string | undefined;
    const { schemes, cdpDomains } = routeTask(task);
    const initialFindings: string[] = [];

    if (runNow) {
      let connection: Awaited<ReturnType<typeof connectToChrome>> | null = null;
      try {
        connection = await connectToChrome({ port, launch, headless, workspaceCwd });
        signal?.throwIfAborted();
        const { session } = connection;
        if (url) {
          await session.send('Page.enable', {});
          await session.send('Page.navigate', { url });
          await new Promise<void>((resolve) => {
            const timer = setTimeout(resolve, 4000);
            (session as unknown as { on(event: string, listener: () => void): void }).on(
              'Page.loadEventFired',
              () => { clearTimeout(timer); resolve(); },
            );
          });
          initialFindings.push(`[AGENT] navigated to ${url}`);
        }
        for (const scheme of schemes.slice(0, 4)) {
          signal?.throwIfAborted();
          const entry = SCHEME_REGISTRY[scheme as keyof typeof SCHEME_REGISTRY];
          if (!entry) continue;
          try {
            const result = await entry.recipe({
              session,
              params: {
                scheme: scheme as ChromeDebugParams['scheme'],
                url: undefined,
                durationMs,
                port,
              },
              screenshotDir: connection.screenshotDir,
              signal: signal ? AbortSignal.any([signal, AbortSignal.timeout(20_000)]) : AbortSignal.timeout(20_000),
            });
            if (result.evidenceLines.length > 0) {
              initialFindings.push(`\n[AGENT] === ${scheme.toUpperCase()} ===`);
              initialFindings.push(...result.evidenceLines);
            }
          } catch (error) {
            signal?.throwIfAborted();
            initialFindings.push(`[AGENT] ${scheme} error: ${(error as Error).message.slice(0, 100)}`);
          }
        }
      } catch (error) {
        signal?.throwIfAborted();
        initialFindings.push(`[AGENT] connect error: ${(error as Error).message}`);
      } finally {
        if (connection) {
          await cleanupConnection(connection.session, !launch, launch).catch(() => {});
        }
      }
    }

    const spawnConfig = buildSpawnConfig({
      task,
      url,
      port,
      model,
      cdpDomains,
      skillContext: '',
      initialFindings,
    });
    spawnParams = {
      task: context ? `## Context\n${context.trim()}\n\n## Task\n${spawnConfig.task}` : spawnConfig.task,
      name: name ?? `Browser Agent · ${getRandomAgentName()}`,
      cwd,
      tools: [...new Set([...spawnConfig.tools, 'MCPTool', 'skill', 'bash'])],
      skills: resolveSubagentSkills(
        SUBAGENT_REGISTRY['browser-agent'],
        cwd ?? ctx?.cwd ?? process.cwd(),
      ),
      systemPrompt: spawnConfig.systemPrompt,
      resourceMode: 'octocode',
      thinking: thinking ?? 'low',
      model: model ?? spawnConfig.model,
      provider: provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  } else if (profile === 'custom') {
    // Custom workers use the Octocode host path by default. Explicit empty
    // tools and explicit lean mode remain available for isolated smith workers.
    const tools = query['tools'] as string[] | undefined;
    const systemPrompt = query['systemPrompt'] as string | undefined;
    const resourceMode =
      (query['resourceMode'] as SpawnAgentParams['resourceMode']) ?? 'octocode';
    const workerCwd = cwd ?? ctx?.cwd ?? process.cwd();
    spawnParams = {
      task: fullTask,
      name: name ?? `Worker · ${getRandomAgentName()}`,
      cwd,
      tools: tools ?? (resourceMode === 'lean' ? [] : ['MCPTool', 'skill', 'bash']),
      skills: resourceMode === 'octocode'
        ? resolveSubagentSkills({}, workerCwd)
        : undefined,
      systemPrompt,
      resourceMode,
      thinking,
      model,
      provider: provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  } else {
    // Typed registry profile (researcher / planner / architect).
    const subagentName = PROFILE_TO_SUBAGENT[profile];
    const config = SUBAGENT_REGISTRY[subagentName] as SubagentConfig & {
      model?: string;
      provider?: string;
    };
    const systemPrompt = loadSystemPrompt(config);
    const skills = resolveSubagentSkills(config, cwd ?? ctx?.cwd ?? process.cwd());
    spawnParams = {
      task: fullTask,
      name: name ?? `${config.label} · ${getRandomAgentName()}`,
      cwd,
      tools: [...config.tools],
      skills,
      systemPrompt,
      resourceMode: config.resourceMode,
      thinking: thinking ?? config.thinking,
      model: model ?? config.model,
      provider: provider ?? config.provider ?? ctx?.model?.provider,
      noSession: query['noSession'] !== false,
      isolation,
      includeUncommitted,
    };
  }

  spawnParams.planStep = planStep;

  signal?.throwIfAborted();
  const approvedParams = await prepareSpawnAgentParams(spawnParams, ctx);
  signal?.throwIfAborted();
  if (assignment) {
    const current = resolvePlanAssignment(assignment.task.id, ctx, assignment.planId);
    if (current.scope !== assignment.scope) throw new Error('Parent plan session changed during worker preparation; retry in the current session.');
    const contract = JSON.stringify({ planId: current.planId, taskId: current.task.id, task: current.task.text,
      paths: current.task.paths ?? [], acceptance: current.task.acceptance, checkCommand: current.task.checkCommand });
    if (contract.length > 12_000) throw new Error('Plan assignment context exceeds 12000 characters; narrow the task contract before delegating.');
    approvedParams.planId = current.planId;
    approvedParams.planScope = current.scope;
    approvedParams.task = `${approvedParams.task}\n\n## Parent plan assignment\n${contract}\nReport evidence and checks to the parent; the parent owns task completion and verification.`;
  }
  signal?.throwIfAborted();
  const record = spawnRpcAgent(approvedParams, ctx);
  refreshAgentLedgerUi(ctx);

  const agentId: string = record.id;
  const ledgerEntry = listWorkerLedgerEntries().find((entry) => entry.agentId === agentId);
  const policyLines =
    record.policyWarnings.length > 0
      ? ['', '[POLICY]', ...record.policyWarnings.map((w: string) => `  ${w}`)]
      : [];

  const output = [
    `[SPAWNED] profile:${profile} · agentId:${agentId}`,
    `[SPAWNED] name: ${record.name}`,
    `[SPAWNED] model: ${ledgerEntry?.provider ? `${ledgerEntry.provider}/` : ''}${ledgerEntry?.model ?? 'inherited'}`,
    `[SPAWNED] task: ${ledgerEntry?.task ?? task}`,
    ...(ledgerEntry?.planStep ? [`[SPAWNED] plan: ${ledgerEntry.planStep}`] : []),
    ...policyLines,
    '',
    `[USAGE] agent({queries:[{reasoning:"…", type:"wait", agentId:"${agentId}"}]})`,
  ].join('\n');

  return {
    content: [{ type: 'text', text: output }],
    details: { agentId, profile, name: record.name, model: ledgerEntry?.model, provider: ledgerEntry?.provider, task: ledgerEntry?.task ?? task, planStep: ledgerEntry?.planStep },
  } as unknown as ToolCallResult;
}

/** Register the single public agent tool. */
export function registerUnifiedAgentTool(
  pi: { registerTool?(def: ToolDefinition): void },
  Type: TypeBoxBuilder,
  registeredToolNames: Set<string>,
  registerFn: RegisterFn,
): void {
  // Workers cannot spawn workers — never register this tool inside a subagent process.
  if (isSubagentProcess()) return;

  // ── Item schema ─────────────────────────────────────────────────────────────
  const operationEnum = stringEnumSchema(
    Type,
    AGENT_OPERATIONS as unknown as string[],
    'Operation: spawn | inspect | wait | message | steer | abort | kill.',
  );
  const profileEnum = stringEnumSchema(
    Type,
    AGENT_PROFILES as unknown as string[],
    'Spawn profile: researcher | planner | architect | browser | custom.',
  );
  const deliveryEnum = stringEnumSchema(
    Type,
    ['send', 'followUp'],
    'Message delivery: send starts a new idle turn; followUp queues after the current turn.',
  );
  const isolationEnum = stringEnumSchema(
    Type,
    ['shared', 'worktree'],
    'Filesystem isolation for spawn. shared (default) uses current cwd; worktree creates an isolated git worktree.',
  );
  const resourceModeEnum = stringEnumSchema(
    Type,
    ['lean', 'octocode', 'default'],
    'Resource mode for custom profile. octocode is the default; lean disables extensions and skills.',
  );

  // All lifecycle-specific fields are optional; type is the discriminator.
  // Google-family schemas require a string enum instead of Type.Union / Type.Literal.
  const itemSchema = Type.Object(
    {
      type: operationEnum as ReturnType<TypeBoxBuilder['String']>,
      // spawn fields
      profile: Type.Optional(profileEnum as ReturnType<TypeBoxBuilder['String']>),
      task: Type.Optional(Type.String({ description: 'Worker assignment/instructions for spawn; not a plan task record.' })),
      context: Type.Optional(Type.String({ description: 'Evidence or constraints prepended to the worker assignment.' })),
      name: Type.Optional(Type.String({ description: 'Human label for the worker (spawn).' })),
      planStep: Type.Optional(Type.String({ description: 'Stable task ID in the executing plan: doing, dependencies done, no pending input or live assigned worker. Omit for standalone work.' })),
      model: Type.Optional(Type.String({ description: 'Model id from `pi -ne --list-models`.' })),
      provider: Type.Optional(Type.String({ description: 'Provider name (required when model id collides with a builtin namespace).' })),
      thinking: Type.Optional(Type.String({ description: 'Thinking level: off|minimal|low|medium|high|xhigh.' })),
      cwd: Type.Optional(Type.String({ description: 'Working directory (spawn).' })),
      isolation: Type.Optional(isolationEnum as ReturnType<TypeBoxBuilder['String']>),
      includeUncommitted: Type.Optional(Type.Boolean({ description: 'With isolation:worktree, apply uncommitted tracked changes.' })),
      // browser profile
      url: Type.Optional(Type.String({ description: 'URL to pass to the browser profile (spawn/browser).' })),
      port: Type.Optional(Type.Integer({ description: 'Chrome remote debug port (spawn/browser, default 9222).' })),
      launch: Type.Optional(Type.Boolean({ description: 'Launch Chrome for initial browser analysis (default false).' })),
      headless: Type.Optional(Type.Boolean({ description: 'Launch Chrome headless for initial browser analysis (default true).' })),
      runNow: Type.Optional(Type.Boolean({ description: 'Run routed initial browser analysis before spawning (default true).' })),
      durationMs: Type.Optional(Type.Integer({ description: 'Initial browser scheme observation window in milliseconds (default 5000).' })),
      workspaceCwd: Type.Optional(Type.String({ description: 'Workspace root for browser screenshots and session paths.' })),
      // custom profile
      tools: Type.Optional(Type.Array(Type.String(), { description: 'Tool allowlist for custom profile. Defaults to MCPTool, skill, and bash; [] requests no tools.' })),
      systemPrompt: Type.Optional(Type.String({ description: 'Extra system prompt for custom profile (spawn).' })),
      resourceMode: Type.Optional(resourceModeEnum as ReturnType<TypeBoxBuilder['String']>),
      noSession: Type.Optional(Type.Boolean({ description: 'Pass --no-session to the spawned worker (default true).' })),
      // lifecycle fields
      agentId: Type.Optional(Type.String({ description: 'Target agent id (inspect/wait/message/steer/abort/kill).' })),
      message: Type.Optional(Type.String({ description: 'Message text (message/steer).' })),
      delivery: Type.Optional(deliveryEnum as ReturnType<TypeBoxBuilder['String']>),
      timeoutMs: Type.Optional(Type.Integer({ description: 'Wait silence budget in milliseconds (default 300000).' })),
      remove: Type.Optional(Type.Boolean({ description: 'Remove the worker record after wait/kill when safe.' })),
      full: Type.Optional(Type.Boolean({ description: 'Return full retained history for inspect/wait/abort/kill.' })),
    },
  );

  const parameters = buildQueryEnvelopeSchema(Type, itemSchema, {
    reasoningDescription: 'Concise reason this agent operation is necessary (max 240 chars).',
  });

  registerFn(pi, registeredToolNames, {
    name: 'agent',
    label: 'Agent',
    description: [
      'Unified agent facade. Spawn typed/custom/browser workers and manage their lifecycle.',
      '',
      'Operations (type field):',
      '  spawn   — create a new worker. Returns agentId.',
      '  inspect — list all agents (no agentId) or show status (with agentId).',
      '  wait    — wait for the current turn, returning a live snapshot after a quiet gap.',
      '  message — send or queue a message (delivery: send|followUp).',
      '  steer   — redirect in-flight turn or queue follow-up.',
      '  abort   — gracefully interrupt the active worker turn without killing the process.',
      '  kill    — terminate a worker process.',
      '',
      'Profiles for spawn:',
      '  researcher — web/GitHub/npm/local research specialist.',
      '  planner    — implementation-planning specialist.',
      '  architect  — local-code / root-cause specialist.',
      '  browser    — Chrome DevTools Protocol specialist; routes task to CDP domains.',
      '  custom     — Octocode-capable worker by default; accepts explicit tools/systemPrompt/resourceMode.',
      '',
      'Same-batch rule: spawn and lifecycle ops with explicit agentIds cannot coexist.',
      'Spawn first, then use the returned agentId in a subsequent call.',
    ].join('\n'),

    promptSnippet:
      'Spawn/manage researcher, planner, architect, browser, or custom workers. Spawn first; use agentId later. Workers use MCPTool for repository research and the harness Awareness CLI for coordination; other shell access follows their role.',
    promptGuidelines: [
      'Use agent when a task needs independent context, its own tools, or parallel execution. Do NOT use agent for tasks a direct tool call, bash, or skill workflow already handles — prefer the simplest surface.',
      'Profile routing: researcher (web+GitHub+local research), planner (implementation planning), architect (root-cause/design), browser (CDP automation), custom (explicit tools/systemPrompt).',
      'Never mix spawn and agentId-bearing lifecycle queries in the same batch — spawn first, lifecycle next call.',
      'Provide a labelled task packet (Goal/Context/Scope/Acceptance/Return) in the task field to avoid vague handoffs.',
      'Use type:wait to collect the current turn before trusting a worker is complete. After wait or inspect, verify any key finding, distill it into session memory.md, and update the user when it changes the hypothesis, plan, risk, or next action; never persist or repeat a raw handback.',
      'Use type:kill after collecting results to free resources.',
      'Use type:inspect without agentId to list all agents; with agentId to check status.',
      'For plan work, start a runnable step first, then pass its stable task id as planStep so the worker receives paths, acceptance, and check contract.',
    ],

    parameters,

    async execute(
      toolCallId: string,
      rawParams: Record<string, unknown>,
      signal?: AbortSignal,
      onUpdate?: unknown,
      ctx?: PiContext,
    ): Promise<ToolCallResult> {
      // Cross-batch reference guard: checked before any item executes.
      const queriesRaw = Array.isArray(rawParams['queries'])
        ? (rawParams['queries'] as QueryRecord[])
        : [];
      rejectCrossBatchReference(queriesRaw);

      return executeQueryBatch({
        toolCallId,
        raw: rawParams,
        signal,
        onUpdate: onUpdate as ((update: ToolCallResult) => void) | undefined,
        ctx,
        passthroughSingle: true,
        preflight: async (query, index) => {
          const type = query['type'] as string | undefined;
          if (!type || !(AGENT_OPERATIONS as readonly string[]).includes(type)) {
            throw new Error(
              `queries[${index}].type must be one of: ${AGENT_OPERATIONS.join(', ')}.`,
            );
          }
          if (type === 'spawn') {
            const task = String(query['task'] ?? '').trim();
            if (!task) throw new Error(`queries[${index}]: spawn requires a non-empty task.`);
            const profile = String(query['profile'] ?? 'custom');
            if (!(AGENT_PROFILES as readonly string[]).includes(profile)) {
              throw new Error(`queries[${index}].profile must be one of: ${AGENT_PROFILES.join(', ')}.`);
            }
            return;
          }
          const agentId = String(query['agentId'] ?? '').trim();
          if (type !== 'inspect' && !agentId) {
            throw new Error(`queries[${index}]: ${type} requires agentId.`);
          }
          if ((type === 'message' || type === 'steer') && !String(query['message'] ?? '').trim()) {
            throw new Error(`queries[${index}]: ${type} requires a non-empty message.`);
          }
        },

        async execute(
          query: QueryRecord,
          _index: number,
          _itemId: string,
          itemSignal?: AbortSignal,
          _itemUpdate?: unknown,
          itemCtx?: PiContext,
        ): Promise<ToolCallResult> {
          const type = query['type'] as AgentOperation;
          if (type === 'spawn') return executeSpawnQuery(query, itemCtx, itemSignal);

          return executeAgentLifecycle(query, itemSignal, itemCtx);
        },

        summarize(result: ToolCallResult, query: QueryRecord) {
          const type = query['type'] as string;
          const text =
            (result.content.find((p) => p.type === 'text') as { text?: string } | undefined)
              ?.text ?? '';
          return `${type}: ${text.split('\n').find(Boolean)?.trim().slice(0, 80) ?? 'ok'}`;
        },
      });
    },

    renderCall(rawParams: unknown) {
      const raw = rawParams as {
        queries?: Array<{ type?: string; profile?: string; agentId?: string; task?: string }>;
      };
      const first = raw?.queries?.[0];
      const op = first?.type ?? '…';
      const detail = first?.profile
        ? ` profile:${first.profile}`
        : first?.agentId
          ? ` id:${String(first.agentId).slice(0, 8)}`
          : first?.task
            ? ` "${String(first.task).slice(0, 36)}${String(first.task).length > 36 ? '…' : ''}"`
            : '';
      const extra =
        (raw?.queries?.length ?? 0) > 1
          ? ` +${(raw.queries?.length ?? 1) - 1}`
          : '';
      return makeComponentRenderer((_props, { width: w }) =>
        [truncateToWidth(`agent(${op}${detail})${extra}`, w)], undefined,
      );
    },

    renderResult(result: unknown, _opts: unknown, theme?: PiTheme) {
      const r = result as {
        content?: Array<{ type: string; text?: string }>;
        isError?: boolean;
      };
      const ok = !r?.isError;
      const text =
        (r?.content?.find((p) => p.type === 'text') as { text?: string } | undefined)?.text ?? '';
      const firstLine = text.split('\n').find(Boolean)?.trim() ?? (ok ? 'done' : 'failed');
      const glyph = ok
        ? paint(theme, 'success', CLI_GLYPH.success)
        : paint(theme, 'error', CLI_GLYPH.error);
      return makeComponentRenderer((_props, { width: w }) =>
        [truncateToWidth(`${glyph} agent · ${firstLine}`, w)], undefined,
      );
    },
  } satisfies ToolDefinition);
}
