name: Publish to npm

on:
  push:
    branches:
      - master
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      newTag: ${{ steps.version.outputs.newTag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: 'Automated Version Bump'
        id: version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: '.'
        with:
          tag-prefix: 'v'
          minor-wording: 'feat,minor'
          major-wording: 'BREAKING CHANGE,major'
          patch-wording: 'fix,patch'
          rc-wording: 'pre-alpha,pre-beta,pre-rc'
          skip-tag: 'false'
          skip-commit: 'false'
          skip-push: 'false'
          default: 'patch'
          commit-message: 'CI: version bump to {{version}} [skip ci]'
          bump-policy: 'all'
          check-last-commit-only: 'false'

  verify:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Enable Corepack for Yarn support
      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Build package
        run: yarn build

  publish:
    needs: [version, verify]
    runs-on: ubuntu-latest
    if: ${{ needs.version.outputs.newTag != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      # Enable Corepack for Yarn support
      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup npmrc for automation
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: yarn npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}