import { HISTORY_ROUTE_DESCRIPTORS } from '../schema/definitions-history.js';

export interface CommandRoute {
  command: string;
  action?: string;
}

export const COMMAND_ROUTES: Record<string, CommandRoute> = {
  ...Object.fromEntries(HISTORY_ROUTE_DESCRIPTORS.map(route => [route.command, { command: route.schema }])),
  'memory record': { command: 'tell-memory' },
  'memory recall': { command: 'get-memory' },
  'memory forget': { command: 'forget' },
  'memory archive': { command: 'memory-archive' },
  'memory restore': { command: 'memory-restore' },
  'lock acquire': { command: 'pre-flight-intent' },
  'lock release': { command: 'release-file-lock' },
  'lock wait': { command: 'wait-for-lock' },
  'lock prune': { command: 'prune-stale-locks' },
  'plan create': { command: 'plan-command', action: 'create' },
  'plan list': { command: 'plan-command', action: 'list' },
  'plan show': { command: 'plan-command', action: 'show' },
  'plan join': { command: 'plan-command', action: 'join' },
  'plan doc': { command: 'plan-command', action: 'doc' },
  'plan status': { command: 'plan-command', action: 'status' },
  'task create': { command: 'task-command', action: 'create' },
  'task list': { command: 'task-command', action: 'list' },
  'task ready': { command: 'task-command', action: 'ready' },
  'task show': { command: 'task-command', action: 'show' },
  'task claim': { command: 'task-command', action: 'claim' },
  'task heartbeat': { command: 'task-command', action: 'heartbeat' },
  'task submit': { command: 'task-command', action: 'submit' },
  'task release': { command: 'task-command', action: 'release' },
  'task retry': { command: 'task-command', action: 'retry' },
  'task depend': { command: 'task-command', action: 'depend' },
  'work start': { command: 'work-command', action: 'start' },
  'work touch': { command: 'work-command', action: 'touch' },
  'work end': { command: 'work-command', action: 'end' },
  'work list': { command: 'work-command', action: 'list' },
  'work show': { command: 'work-command', action: 'show' },
  'verify mark': { command: 'verify' },
  'verify audit': { command: 'audit-unverified' },
  'refinement set': { command: 'refine-set' },
  'refinement get': { command: 'refine-get' },
  'refinement delete': { command: 'refine-delete' },
  'signal publish': { command: 'agent-signal', action: 'publish' },
  'signal list': { command: 'agent-signal', action: 'list' },
  'signal reply': { command: 'agent-signal', action: 'reply' },
  'signal ack': { command: 'agent-signal', action: 'ack' },
  'signal resolve': { command: 'agent-signal', action: 'resolve' },
  'signal prune': { command: 'notify-prune' },
  'agent register': { command: 'agent-registry', action: 'register' },
  'agent list': { command: 'agent-registry', action: 'list' },
  'session capture': { command: 'session-capture' },
  'reflect record': { command: 'reflect' },
  'reflect mine-weakness': { command: 'mine-weakness' },
  'reflect export-harness': { command: 'export-harness' },
  'reflect developer-review': { command: 'developer-review' },
  'docs list': { command: 'docs-catalog', action: 'list' },
  'docs show': { command: 'docs-catalog', action: 'show' },
  'docs staleness': { command: 'doc-staleness' },
  'skill install': { command: 'skill-install' },
  'maintenance digest': { command: 'digest' },
  'maintenance init': { command: 'init' },
  'maintenance self-test': { command: 'self-test' },
  'config show': { command: 'awareness-config', action: 'show' },
  'config init': { command: 'awareness-config', action: 'init' },
  'config validate': { command: 'awareness-config', action: 'validate' },
};
